[package]
name = "pe-18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iter_tools = { version = "0.1.4", features = ["full"] }
pe_utils = { path = "../pe-utils" }
